version: '3'
services:
    zookeeper:
        image: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: wurstmeister/kafka
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        depends_on:
            - zookeeper
    configservice:
        build: ./configservice
        ports:
            - '8080:8080' 
    vendaservice:
        build: ./vendaservice
        links:
            - kafka
            - vendaservicedb
            - gatewayservice
            - configservice
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVER: 'kafka:9092'
            CONFIG_SERVER: 'http://configservice:8080'
        depends_on:
            - configservice
        ports:
            - '8084:8084'
    vendaservicedb:
        image: mongo
        ports:
            - '27018:27017'    
    estoqueservice:
        build: ./estoqueservice
        links:
            - kafka
            - estoqueservicedb
            - gatewayservice
            - configservice
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVER: 'kafka:9092'
            CONFIG_SERVER: 'http://configservice:8080'
        depends_on:
            - configservice
        ports:
            - '8083:8083'
    estoqueservicedb:
        image: mongo
        ports:
            - '27020:27017'